// @vitest-environment node
//
// Unit tests for readJpegExifOrientation — the pure-JS EXIF orientation reader
// used by the sideways-photo detector.
//
// Two suites:
//  1. Synthetic buffers — built in memory to pin exact byte-level behaviour.
//  2. Fixture files    — realistic multi-entry EXIF JPEGs generated by
//     server/__fixtures__/generate-fixtures.cjs to mirror the layouts
//     that iPhone (little-endian TIFF) and Android (big-endian TIFF) cameras
//     produce in the field.
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { readJpegExifOrientation } from "./photoExif";

function fixture(name: string): Buffer {
  return readFileSync(join(__dirname, "__fixtures__", name));
}

// ---------------------------------------------------------------------------
// Helpers: build minimal synthetic JPEG buffers with a real APP1/EXIF segment.
// ---------------------------------------------------------------------------

/**
 * Write a 2-byte big-endian unsigned integer into buf at offset.
 */
function writeU16BE(buf: Buffer, offset: number, value: number) {
  buf[offset] = (value >> 8) & 0xff;
  buf[offset + 1] = value & 0xff;
}

/**
 * Write a 4-byte little-endian unsigned integer into buf at offset.
 */
function writeU32LE(buf: Buffer, offset: number, value: number) {
  buf.writeUInt32LE(value, offset);
}

/**
 * Write a 2-byte little-endian unsigned integer into buf at offset.
 */
function writeU16LE(buf: Buffer, offset: number, value: number) {
  buf.writeUInt16LE(value, offset);
}

/**
 * Write a 4-byte big-endian unsigned integer into buf at offset.
 */
function writeU32BE(buf: Buffer, offset: number, value: number) {
  buf.writeUInt32BE(value, offset);
}

/**
 * Build a minimal JPEG with a single APP1/EXIF segment containing one IFD0
 * entry: the Orientation tag (0x0112) set to `orientation`.
 *
 * Layout (little-endian TIFF):
 *   SOI (2) | APP1 marker (2) | APP1 length (2) | "Exif\0\0" (6)
 *   TIFF header: byte-order (2) + magic 42 (2) + IFD0 offset (4) = 8
 *   IFD0: entry count (2) + one 12-byte entry + next-IFD ptr (4)
 *   Entry: tag (2) + type SHORT (2) + count 1 (4) + value (2) + pad (2)
 */
function buildJpegWithOrientation(orientation: number): Buffer {
  // Sizes (all at TIFF-relative offsets):
  //   TIFF header = 8 bytes, IFD0 starts right after → offset 8
  //   IFD0 = 2 (count) + 12 (one entry) + 4 (next IFD) = 18 bytes
  const tiffSize = 8 + 18; // 26 bytes

  // APP1 payload = "Exif\0\0" (6) + TIFF (26) = 32 bytes
  // APP1 segment length field (big-endian) includes the 2-byte length field itself
  // so segLen = 2 + 32 = 34, but the actual bytes written after the length field
  // are 32. The length field value (per JFIF spec) = payload + 2 = 34.
  const exifPayloadSize = 6 + tiffSize; // 32
  const app1SegLen = 2 + exifPayloadSize; // 34 (length field value)

  // Total buffer: SOI(2) + APP1marker(2) + lenField(2) + exifPayload(32) + EOI(2) = 40
  const totalSize = 2 + 2 + 2 + exifPayloadSize + 2;
  const buf = Buffer.alloc(totalSize, 0);

  let pos = 0;

  // SOI
  buf[pos++] = 0xff;
  buf[pos++] = 0xd8;

  // APP1 marker
  buf[pos++] = 0xff;
  buf[pos++] = 0xe1;

  // APP1 segment length (big-endian, includes the 2-byte length field)
  writeU16BE(buf, pos, app1SegLen);
  pos += 2;

  // "Exif\0\0"
  buf.write("Exif\0\0", pos, "latin1");
  pos += 6;

  // TIFF header (little-endian: 'II')
  const tiffBase = pos;
  buf[pos++] = 0x49; // 'I'
  buf[pos++] = 0x49; // 'I'
  writeU16LE(buf, pos, 42); // TIFF magic
  pos += 2;
  writeU32LE(buf, pos, 8); // IFD0 offset from TIFF header start = 8
  pos += 4;

  // IFD0 (starts at tiffBase + 8)
  writeU16LE(buf, pos, 1); // entry count = 1
  pos += 2;

  // IFD0 entry: Orientation tag
  writeU16LE(buf, pos, 0x0112); // tag = Orientation
  pos += 2;
  writeU16LE(buf, pos, 3); // type = SHORT
  pos += 2;
  writeU32LE(buf, pos, 1); // count = 1
  pos += 4;
  writeU16LE(buf, pos, orientation); // value
  pos += 2;
  writeU16LE(buf, pos, 0); // padding (value offset is 4 bytes; SHORT is 2, pad with 0)
  pos += 2;

  // next IFD pointer = 0 (no more IFDs)
  writeU32LE(buf, pos, 0);
  pos += 4;

  // EOI
  buf[pos++] = 0xff;
  buf[pos++] = 0xd9;

  // Verify our layout math is correct
  if (pos !== totalSize) {
    throw new Error(`Layout error: wrote ${pos} bytes, expected ${totalSize}`);
  }

  // Sanity check: TIFF IFD0 address
  void tiffBase;

  return buf;
}

/**
 * Build a minimal JPEG with a single APP1/EXIF segment containing one IFD0
 * entry: the Orientation tag (0x0112) set to `orientation`.
 *
 * This is the big-endian ('MM') counterpart of buildJpegWithOrientation.
 *
 * Layout (big-endian TIFF):
 *   SOI (2) | APP1 marker (2) | APP1 length (2) | "Exif\0\0" (6)
 *   TIFF header: byte-order 'MM' (2) + magic 42 BE (2) + IFD0 offset BE (4) = 8
 *   IFD0: entry count BE (2) + one 12-byte entry + next-IFD ptr BE (4)
 *   Entry: tag BE (2) + type SHORT BE (2) + count BE (4) + value BE (2) + pad (2)
 */
function buildJpegWithOrientationBE(orientation: number): Buffer {
  const tiffSize = 8 + 18; // 26 bytes (same layout as LE version)
  const exifPayloadSize = 6 + tiffSize; // 32
  const app1SegLen = 2 + exifPayloadSize; // 34

  const totalSize = 2 + 2 + 2 + exifPayloadSize + 2;
  const buf = Buffer.alloc(totalSize, 0);

  let pos = 0;

  // SOI
  buf[pos++] = 0xff;
  buf[pos++] = 0xd8;

  // APP1 marker
  buf[pos++] = 0xff;
  buf[pos++] = 0xe1;

  // APP1 segment length (big-endian)
  writeU16BE(buf, pos, app1SegLen);
  pos += 2;

  // "Exif\0\0"
  buf.write("Exif\0\0", pos, "latin1");
  pos += 6;

  // TIFF header (big-endian: 'MM')
  buf[pos++] = 0x4d; // 'M'
  buf[pos++] = 0x4d; // 'M'
  writeU16BE(buf, pos, 42); // TIFF magic (big-endian)
  pos += 2;
  writeU32BE(buf, pos, 8); // IFD0 offset from TIFF header start = 8
  pos += 4;

  // IFD0 (starts at TIFF base + 8)
  writeU16BE(buf, pos, 1); // entry count = 1
  pos += 2;

  // IFD0 entry: Orientation tag (all fields big-endian)
  writeU16BE(buf, pos, 0x0112); // tag = Orientation
  pos += 2;
  writeU16BE(buf, pos, 3); // type = SHORT
  pos += 2;
  writeU32BE(buf, pos, 1); // count = 1
  pos += 4;
  writeU16BE(buf, pos, orientation); // value (first 2 bytes of the 4-byte value field)
  pos += 2;
  writeU16BE(buf, pos, 0); // padding
  pos += 2;

  // next IFD pointer = 0 (no more IFDs)
  writeU32BE(buf, pos, 0);
  pos += 4;

  // EOI
  buf[pos++] = 0xff;
  buf[pos++] = 0xd9;

  if (pos !== totalSize) {
    throw new Error(`Layout error: wrote ${pos} bytes, expected ${totalSize}`);
  }

  return buf;
}

/**
 * Build a minimal JPEG with no APP1 segment (just SOI + EOI).
 */
function buildJpegNoExif(): Buffer {
  return Buffer.from([0xff, 0xd8, 0xff, 0xd9]);
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("readJpegExifOrientation — synthetic single-entry buffers", () => {
  it("returns 6 for a JPEG with Orientation=6 (90° CW — most common iPhone portrait)", () => {
    const buf = buildJpegWithOrientation(6);
    expect(readJpegExifOrientation(buf)).toBe(6);
  });

  it("returns 1 for a JPEG with Orientation=1 (upright — must not appear in candidates)", () => {
    const buf = buildJpegWithOrientation(1);
    expect(readJpegExifOrientation(buf)).toBe(1);
  });

  it("returns null for a JPEG with no EXIF segment", () => {
    const buf = buildJpegNoExif();
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // Reload-safety invariant: canvas.toDataURL('image/jpeg') produces a JPEG
  // with no EXIF APP1 segment. After runFleetFix / runPhotoFix re-uploads a
  // photo via the canvas path, the stored bytes look like buildJpegNoExif().
  // The scan filter is `orientation !== null && orientation !== 1`. Because
  // null is excluded by that test, fixed photos never reappear as candidates
  // in a fresh scan after a page reload — no client-side "fixed IDs" set is
  // needed to prevent double-fixing.
  it("canvas-fixed photo (no EXIF) is excluded from scan candidates on reload", () => {
    // Simulate the bytes stored after orientedJpegDataUrl() re-upload:
    // a plain JPEG with no APP1/EXIF block.
    const fixedBuf = buildJpegNoExif();
    const orientation = readJpegExifOrientation(fixedBuf);
    expect(orientation).toBeNull();
    // Confirm the candidate-filter predicate is false for a fixed photo:
    expect(orientation !== null && orientation !== 1).toBe(false);
  });

  it("returns null for a non-JPEG buffer without throwing", () => {
    const buf = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]); // PNG header
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  it("returns null for an empty buffer without throwing", () => {
    expect(readJpegExifOrientation(Buffer.alloc(0))).toBeNull();
  });

  it("returns 8 for Orientation=8 (90° CCW — phone portrait stored sideways the other way)", () => {
    const buf = buildJpegWithOrientation(8);
    expect(readJpegExifOrientation(buf)).toBe(8);
  });

  it("returns 3 for Orientation=3 (180° rotation)", () => {
    const buf = buildJpegWithOrientation(3);
    expect(readJpegExifOrientation(buf)).toBe(3);
  });

  // ---- Big-endian ('MM') TIFF synthetic buffers ---------------------------
  // These exercise the BE branch (buf[t] !== 0x49) of readJpegExifOrientation,
  // which is used by many Android OEM cameras.

  it("BE TIFF: returns 6 for Orientation=6 (90° CW — Android portrait)", () => {
    const buf = buildJpegWithOrientationBE(6);
    expect(readJpegExifOrientation(buf)).toBe(6);
  });

  it("BE TIFF: returns 1 for Orientation=1 (upright — must not appear in sideways candidates)", () => {
    const buf = buildJpegWithOrientationBE(1);
    expect(readJpegExifOrientation(buf)).toBe(1);
  });

  it("BE TIFF: returns 8 for Orientation=8 (90° CCW — Android portrait rotated the other way)", () => {
    const buf = buildJpegWithOrientationBE(8);
    expect(readJpegExifOrientation(buf)).toBe(8);
  });
});

// ---------------------------------------------------------------------------
// Suite 1b: BE TIFF truncated-buffer safety.
//
// A broken Android camera app (or a network-corrupted upload) can produce a
// JPEG whose APP1/EXIF payload is cut off mid-TIFF-header.  These tests prove
// that every early-exit bounds check in readJpegExifOrientation fires for
// big-endian ('MM') TIFF headers and that the function returns null rather
// than throwing a RangeError.
//
// Full BE buffer layout (40 bytes total, all offsets absolute):
//   0–1   SOI
//   2–3   APP1 marker
//   4–5   APP1 length (big-endian, = 34)
//   6–11  "Exif\0\0"
//   12–13 TIFF byte-order mark ('M','M')   ← t = 12
//   14–15 TIFF magic 42 (big-endian)
//   16–19 IFD0 offset = 8 (big-endian)
//   20–21 IFD0 entry count = 1              ← ifd0 = t + 8 = 20
//   22–33 12-byte IFD0 entry                ← e = ifd0 + 2 = 22
//   34–37 next-IFD pointer = 0
//   38–39 EOI
//
// Bounds checks under test (from photoExif.ts):
//   A) if (t + 8 >= buf.length) break          → fires when len ≤ 20
//   B) if (ifd0 + 2 >= buf.length) break       → fires when len ≤ 22
//   C) if (e + 10 >= buf.length) break (loop)  → fires when len ≤ 32
// ---------------------------------------------------------------------------

/**
 * Build a minimal BE TIFF JPEG and slice it to `keepBytes` to simulate a
 * truncated upload.  The APP1 length field is deliberately left at the
 * full-buffer value so the segment-walk does not skip the segment — the
 * only difference is that the buffer ends prematurely.
 */
function buildTruncatedJpegBE(orientation: number, keepBytes: number): Buffer {
  return buildJpegWithOrientationBE(orientation).subarray(0, keepBytes);
}

describe("readJpegExifOrientation — BE TIFF truncated-buffer safety", () => {
  // ---- Check A: buffer ends just after the 'MM' byte-order mark ----------
  // keepBytes=14 → buffer covers SOI + APP1 marker + APP1 len + "Exif\0\0" +
  // 'M','M' only (2 bytes of the TIFF header).  The IFD0 offset field
  // (pos 16–19) is missing, so `t + 8 >= buf.length` (20 >= 14) fires.
  it("BE TIFF truncated after byte-order mark: returns null without throwing", () => {
    const buf = buildTruncatedJpegBE(6, 14);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // ---- Check B: buffer ends inside the IFD0 count field ------------------
  // keepBytes=21 → the IFD0 count field at pos 20–21 is only partially
  // present (1 byte).  `ifd0 + 2 >= buf.length` (22 >= 21) fires.
  it("BE TIFF truncated inside IFD0 count field: returns null without throwing", () => {
    const buf = buildTruncatedJpegBE(6, 21);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // ---- Check C: buffer ends mid-entry ------------------------------------
  // keepBytes=28 → the entry starts at pos 22; we have tag (22–23) and type
  // (24–25) and the first two bytes of the 4-byte count field (26–27) but
  // the value field at pos 30–31 is absent.  `e + 10 >= buf.length`
  // (32 >= 28) fires on the first loop iteration.
  it("BE TIFF truncated mid-entry (past count, before value): returns null without throwing", () => {
    const buf = buildTruncatedJpegBE(6, 28);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });
});

// ---------------------------------------------------------------------------
// Suite 1c: LE TIFF truncated-buffer safety.
//
// A broken iOS camera app (or a network-corrupted upload) can produce a JPEG
// whose APP1/EXIF payload is cut off mid-TIFF-header.  These tests prove that
// every early-exit bounds check in readJpegExifOrientation fires for
// little-endian ('II') TIFF headers and that the function returns null rather
// than throwing a RangeError.
//
// Full LE buffer layout (40 bytes total, all offsets absolute):
//   0–1   SOI
//   2–3   APP1 marker
//   4–5   APP1 length (big-endian, = 34)
//   6–11  "Exif\0\0"
//   12–13 TIFF byte-order mark ('I','I')   ← t = 12
//   14–15 TIFF magic 42 (little-endian)
//   16–19 IFD0 offset = 8 (little-endian)
//   20–21 IFD0 entry count = 1              ← ifd0 = t + 8 = 20
//   22–33 12-byte IFD0 entry                ← e = ifd0 + 2 = 22
//   34–37 next-IFD pointer = 0
//   38–39 EOI
//
// Bounds checks under test (from photoExif.ts) — identical to the BE path:
//   A) if (t + 8 >= buf.length) break          → fires when len ≤ 20
//   B) if (ifd0 + 2 >= buf.length) break       → fires when len ≤ 22
//   C) if (e + 10 >= buf.length) break (loop)  → fires when len ≤ 32
// ---------------------------------------------------------------------------

/**
 * Build a minimal LE TIFF JPEG and slice it to `keepBytes` to simulate a
 * truncated upload.  The APP1 length field is deliberately left at the
 * full-buffer value so the segment-walk does not skip the segment — the
 * only difference is that the buffer ends prematurely.
 */
function buildTruncatedJpegLE(orientation: number, keepBytes: number): Buffer {
  return buildJpegWithOrientation(orientation).subarray(0, keepBytes);
}

describe("readJpegExifOrientation — LE TIFF truncated-buffer safety", () => {
  // ---- Check A: buffer ends just after the 'II' byte-order mark ----------
  // keepBytes=14 → buffer covers SOI + APP1 marker + APP1 len + "Exif\0\0" +
  // 'I','I' only (2 bytes of the TIFF header).  The IFD0 offset field
  // (pos 16–19) is missing, so `t + 8 >= buf.length` (20 >= 14) fires.
  it("LE TIFF truncated after byte-order mark: returns null without throwing", () => {
    const buf = buildTruncatedJpegLE(6, 14);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // ---- Check B: buffer ends inside the IFD0 count field ------------------
  // keepBytes=21 → the IFD0 count field at pos 20–21 is only partially
  // present (1 byte).  `ifd0 + 2 >= buf.length` (22 >= 21) fires.
  it("LE TIFF truncated inside IFD0 count field: returns null without throwing", () => {
    const buf = buildTruncatedJpegLE(6, 21);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // ---- Check C: buffer ends mid-entry ------------------------------------
  // keepBytes=28 → the entry starts at pos 22; we have tag (22–23) and type
  // (24–25) and the first two bytes of the 4-byte count field (26–27) but
  // the value field at pos 30–31 is absent.  `e + 10 >= buf.length`
  // (32 >= 28) fires on the first loop iteration.
  it("LE TIFF truncated mid-entry (past count, before value): returns null without throwing", () => {
    const buf = buildTruncatedJpegLE(6, 28);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });
});

// ---------------------------------------------------------------------------
// Suite 1d: Corrupt TIFF magic number and out-of-bounds IFD0 offset safety.
//
// readJpegExifOrientation now validates that the TIFF magic number equals 42
// after accepting the byte-order mark.  A partial overwrite of the EXIF block
// (e.g. a corrupt upload) can flip those two bytes without touching 'II'/'MM'.
// An equally dangerous failure mode is a valid magic but a garbage IFD0 offset
// that points past the end of the buffer (e.g. 0xFFFFFFFF from a bit-flip,
// a value equal to buf.length, or the smallest value that places ifd0 + 2
// beyond the last byte).
//
// Full buffer layout (40 bytes total, offsets absolute):
//   0–1   SOI
//   2–3   APP1 marker
//   4–5   APP1 length
//   6–11  "Exif\0\0"
//   12–13 TIFF byte-order mark ('I','I' or 'M','M')   ← t = 12
//   14–15 TIFF magic (LE: 0x2A 0x00 = 42; BE: 0x00 0x2A = 42)
//   16–19 IFD0 offset (LE/BE; value = 8 → ifd0 = t + 8 = 20)
//   20–21 IFD0 entry count = 1                         ← ifd0 = 20
//   22–33 12-byte IFD0 entry                           ← e = 22
//   34–37 next-IFD pointer = 0
//   38–39 EOI
//
// Magic corruption: overwrite bytes 14–15 with a value ≠ 42.
// Offset corruption: overwrite bytes 16–19 with an out-of-range value.
//
// Bounds check under test (photoExif.ts):
//   const ifd0 = t + r32(t + 4);
//   if (ifd0 + 2 >= buf.length) break;   ← fires whenever offset is too large
// ---------------------------------------------------------------------------

/**
 * Build a valid LE-TIFF JPEG and overwrite the 4-byte IFD0 offset field
 * (at absolute position 16) with `badOffset` (written little-endian).
 * Everything else in the TIFF header is correct so the only flaw is the
 * offset itself.
 */
function buildJpegWithBadIfd0OffsetLE(badOffset: number): Buffer {
  const buf = buildJpegWithOrientation(6).slice(); // copy so we can mutate
  // TIFF base t = 12; offset field is at t + 4 = 16
  buf.writeUInt32LE(badOffset, 16);
  return buf;
}

/**
 * Big-endian counterpart of buildJpegWithBadIfd0OffsetLE.
 * The IFD0 offset field is at the same absolute position (16) but is
 * written big-endian.
 */
function buildJpegWithBadIfd0OffsetBE(badOffset: number): Buffer {
  const buf = buildJpegWithOrientationBE(6).slice(); // copy so we can mutate
  // TIFF base t = 12; offset field is at t + 4 = 16
  buf.writeUInt32BE(badOffset, 16);
  return buf;
}

/**
 * Build a JPEG where the APP1/EXIF segment is preceded by a dummy APP2 segment,
 * pushing the TIFF base `t` to absolute position 34 instead of 12.
 * The IFD0 offset field is then set to `badOffset` (written little-endian).
 *
 * Buffer layout (62 bytes total):
 *   0–1   SOI
 *   2–3   APP2 marker  (FF E2)
 *   4–5   APP2 length  = 20  (includes the 2-byte length field)
 *   6–23  APP2 payload (18 zero bytes)
 *   24–25 APP1 marker  (FF E1)
 *   26–27 APP1 length  = 34
 *   28–33 "Exif\0\0"
 *   34–35 TIFF byte-order mark 'II'   ← t = 34
 *   36–37 TIFF magic = 42 (LE)
 *   38–41 IFD0 offset  ← overwritten with badOffset
 *   42–43 IFD0 entry count = 1        ← ifd0 = t + badOffset = 34 + badOffset
 *   44–55 12-byte IFD0 entry
 *   56–59 next-IFD pointer = 0
 *   60–61 EOI
 *
 * With badOffset = 0xFFFFFFFF:  ifd0 = 34 + 4 294 967 295 = 4 294 967 329
 *   → well within JS's safe-integer range; ifd0 + 2 >= 62 so guard fires.
 */
function buildJpegWithLateExifAndBadOffsetLE(badOffset: number): Buffer {
  // Start from the valid minimal LE JPEG (40 bytes) and prepend a dummy APP2.
  const validBuf = buildJpegWithOrientation(6);

  // Dummy APP2: marker(2) + length field(2) + 18-byte payload = 22 bytes.
  const dummySegBodyLen = 18;
  const dummySegLen = 2 + dummySegBodyLen; // length field value = 20

  // Total: SOI(2) + APP2(22) + validBuf-without-SOI(38) = 62 bytes.
  const totalSize = 2 + 2 + 2 + dummySegBodyLen + (validBuf.length - 2);
  const buf = Buffer.alloc(totalSize, 0);
  let pos = 0;

  // SOI
  buf[pos++] = 0xff;
  buf[pos++] = 0xd8;

  // Dummy APP2 segment
  buf[pos++] = 0xff;
  buf[pos++] = 0xe2;
  writeU16BE(buf, pos, dummySegLen);
  pos += 2;
  pos += dummySegBodyLen; // 18 zero bytes

  // Copy the valid JPEG from byte 2 onwards (skip its SOI).
  validBuf.copy(buf, pos, 2);

  // Overwrite the IFD0 offset field.
  // In the new buffer t = 34; the offset field is at t + 4 = 38.
  buf.writeUInt32LE(badOffset, 38);

  return buf;
}

/**
 * Big-endian counterpart of buildJpegWithLateExifAndBadOffsetLE.
 * The TIFF base `t` is 34 (same layout, same dummy APP2 prefix); the IFD0
 * offset field is overwritten big-endian.
 */
function buildJpegWithLateExifAndBadOffsetBE(badOffset: number): Buffer {
  const validBuf = buildJpegWithOrientationBE(6);

  const dummySegBodyLen = 18;
  const dummySegLen = 2 + dummySegBodyLen;

  const totalSize = 2 + 2 + 2 + dummySegBodyLen + (validBuf.length - 2);
  const buf = Buffer.alloc(totalSize, 0);
  let pos = 0;

  buf[pos++] = 0xff;
  buf[pos++] = 0xd8;

  buf[pos++] = 0xff;
  buf[pos++] = 0xe2;
  writeU16BE(buf, pos, dummySegLen);
  pos += 2;
  pos += dummySegBodyLen;

  validBuf.copy(buf, pos, 2);

  // t = 34; IFD0 offset field at t + 4 = 38 (big-endian).
  buf.writeUInt32BE(badOffset, 38);

  return buf;
}

describe("readJpegExifOrientation — corrupt TIFF magic and out-of-bounds IFD0 offset", () => {
  // ---- BE TIFF with magic ≠ 42 -------------------------------------------
  // Build a valid BE buffer, then replace magic bytes (14–15) with 0x00 0x2B
  // (= 43 in big-endian). The byte-order mark 'MM' is intact, so the reader
  // reaches the magic check — it must reject and return null.
  it("BE TIFF with magic = 43 (not 42): returns null without throwing", () => {
    const buf = buildJpegWithOrientationBE(6).slice();
    // absolute offset 14 = t + 2 where t = 12; big-endian magic
    buf[14] = 0x00;
    buf[15] = 0x2b; // 43 in BE
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // ---- LE TIFF with magic ≠ 42 -------------------------------------------
  // Build a valid LE buffer, then replace magic bytes (14–15) with 0x2B 0x00
  // (= 43 in little-endian). The byte-order mark 'II' is intact.
  it("LE TIFF with magic = 43 (not 42): returns null without throwing", () => {
    const buf = buildJpegWithOrientation(6).slice();
    // absolute offset 14 = t + 2 where t = 12; little-endian magic
    buf[14] = 0x2b; // 43 in LE
    buf[15] = 0x00;
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // ---- BE TIFF with magic = 0 (all-zero corruption) ----------------------
  it("BE TIFF with magic = 0 (zero-fill corruption): returns null without throwing", () => {
    const buf = buildJpegWithOrientationBE(6).slice();
    buf[14] = 0x00;
    buf[15] = 0x00;
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // ---- LE TIFF with magic = 0 (all-zero corruption) ----------------------
  it("LE TIFF with magic = 0 (zero-fill corruption): returns null without throwing", () => {
    const buf = buildJpegWithOrientation(6).slice();
    buf[14] = 0x00;
    buf[15] = 0x00;
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // ---- Valid magic, IFD0 offset = 0xFFFFFFFF (BE) ------------------------
  // ifd0 = t(12) + 0xFFFFFFFF = 4294967307, far past buf.length(40).
  it("BE TIFF with valid magic but IFD0 offset = 0xFFFFFFFF: returns null without throwing", () => {
    const buf = buildJpegWithBadIfd0OffsetBE(0xffffffff);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // ---- Valid magic, IFD0 offset = buf.length (BE) ------------------------
  it("BE TIFF with valid magic but IFD0 offset = buf.length: returns null without throwing", () => {
    const buf = buildJpegWithBadIfd0OffsetBE(40 /* buf.length of the valid JPEG */);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // ---- Valid magic, IFD0 offset one past end (BE) ------------------------
  // buf.length = 40; t = 12; ifd0 = 12 + 29 = 41 > 40 → guard fires.
  it("BE TIFF with valid magic but IFD0 offset one past end: returns null without throwing", () => {
    const buf = buildJpegWithBadIfd0OffsetBE(29);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // ---- Valid magic, IFD0 offset = 0xFFFFFFFF (LE) ------------------------
  it("LE TIFF with valid magic but IFD0 offset = 0xFFFFFFFF: returns null without throwing", () => {
    const buf = buildJpegWithBadIfd0OffsetLE(0xffffffff);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // ---- Valid magic, IFD0 offset = buf.length (LE) ------------------------
  it("LE TIFF with valid magic but IFD0 offset = buf.length: returns null without throwing", () => {
    const buf = buildJpegWithBadIfd0OffsetLE(40 /* buf.length of the valid JPEG */);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // ---- Valid magic, IFD0 offset one past end (LE) ------------------------
  it("LE TIFF with valid magic but IFD0 offset one past end: returns null without throwing", () => {
    const buf = buildJpegWithBadIfd0OffsetLE(29);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // ---- Late TIFF base (t=34) + near-max IFD0 offset (LE) -----------------
  //
  // These cases exercise the overflow-safety concern: `ifd0 = t + r32(t+4)`
  // uses JS number arithmetic.  When `t` is large (APP1 comes after a
  // preceding segment) and the offset is near 0xFFFFFFFF, the sum is ~4.3e9 —
  // well inside JS's 2^53 safe-integer range so no precision is lost.
  // The guard `ifd0 + 2 >= buf.length` must still fire and return null.
  //
  // Buffer layout: SOI + APP2(22 bytes) + APP1/EXIF/LE-TIFF + EOI = 62 bytes.
  //   t = 34 (TIFF base is 22 bytes later than in the minimal 40-byte buffer).
  //   badOffset = 0xFFFFFFFF → ifd0 = 34 + 4 294 967 295 = 4 294 967 329
  //   ifd0 + 2 = 4 294 967 331 >= 62 → guard fires.

  it("LE TIFF, late t=34, IFD0 offset=0xFFFFFFFF: guard fires, returns null without throwing", () => {
    const buf = buildJpegWithLateExifAndBadOffsetLE(0xffffffff);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  it("LE TIFF, late t=34, IFD0 offset=0xFFFFFFFE: guard fires, returns null without throwing", () => {
    // badOffset = 0xFFFFFFFE → ifd0 = 34 + 4 294 967 294 = 4 294 967 328
    // ifd0 + 2 = 4 294 967 330 >= 62 → guard fires.
    const buf = buildJpegWithLateExifAndBadOffsetLE(0xfffffffe);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  it("LE TIFF, late t=34, IFD0 offset=0x80000000 (high bit set): returns null without throwing", () => {
    // badOffset = 2 147 483 648 → ifd0 = 34 + 2 147 483 648 = 2 147 483 682
    // ifd0 + 2 = 2 147 483 684 >= 62 → guard fires.
    const buf = buildJpegWithLateExifAndBadOffsetLE(0x80000000);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // ---- Late TIFF base (t=34) + near-max IFD0 offset (BE) -----------------
  //
  // Same scenario with a big-endian ('MM') TIFF header.
  //   t = 34; badOffset = 0xFFFFFFFF → ifd0 = 4 294 967 329; buf.length = 62.

  it("BE TIFF, late t=34, IFD0 offset=0xFFFFFFFF: guard fires, returns null without throwing", () => {
    const buf = buildJpegWithLateExifAndBadOffsetBE(0xffffffff);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  it("BE TIFF, late t=34, IFD0 offset=0xFFFFFFFE: guard fires, returns null without throwing", () => {
    const buf = buildJpegWithLateExifAndBadOffsetBE(0xfffffffe);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  it("BE TIFF, late t=34, IFD0 offset=0x80000000 (high bit set): returns null without throwing", () => {
    const buf = buildJpegWithLateExifAndBadOffsetBE(0x80000000);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });
});

// ---------------------------------------------------------------------------
// Suite 1e: Near-max IFD0 entry count (count = 0xFFFF = 65535) safety.
//
// The IFD0 entry count is a 16-bit unsigned integer, so an adversarial or
// corrupt buffer can set it to 65535 entries.  The per-iteration guard
//   if (e + 10 >= buf.length) break;
// must fire before any out-of-bounds read occurs.  These tests verify that
// readJpegExifOrientation returns null without throwing for both LE ('II')
// and BE ('MM') TIFF variants when count = 0xFFFF.
//
// Two sub-cases per byte-order:
//
//   (a) Short buffer — buffer is truncated so that the very first entry
//       (i=0) fails the bounds check immediately.
//       Buffer layout (40 bytes normally, trimmed to 28):
//         ifd0 = 20, e[0] = 22, e[0]+10 = 32 >= 28 → guard fires on i=0.
//
//   (b) One non-Orientation entry, full buffer — count = 0xFFFF but the
//       single entry present in the buffer has tag ≠ 0x0112 (we flip it to
//       0x010F = Make).  The loop reads entry 0 (no match), then on i=1:
//         e[1] = 34, e[1]+10 = 44 >= 40 → guard fires → returns null.
//
// Buffer layout (40 bytes, absolute offsets, same for LE and BE):
//   0–1   SOI
//   2–3   APP1 marker
//   4–5   APP1 length (= 34)
//   6–11  "Exif\0\0"
//   12–13 TIFF byte-order mark ('I','I' or 'M','M')  ← t = 12
//   14–15 TIFF magic = 42
//   16–19 IFD0 offset = 8 → ifd0 = t + 8 = 20
//   20–21 IFD0 entry count  ← overwritten with 0xFFFF
//   22–33 12-byte IFD0 entry                          ← e[0] = 22
//   34–37 next-IFD pointer = 0
//   38–39 EOI
// ---------------------------------------------------------------------------

/**
 * Build a minimal LE-TIFF JPEG, overwrite the IFD0 entry count with 0xFFFF,
 * then truncate the buffer to `keepBytes`.
 */
function buildJpegWithMaxEntryCountLE(keepBytes: number): Buffer {
  const buf = buildJpegWithOrientation(6).slice(); // mutable copy
  // ifd0 = 20; entry count field is at ifd0 = 20 (little-endian)
  buf.writeUInt16LE(0xffff, 20);
  return buf.subarray(0, keepBytes);
}

/**
 * Build a minimal BE-TIFF JPEG, overwrite the IFD0 entry count with 0xFFFF,
 * then truncate the buffer to `keepBytes`.
 */
function buildJpegWithMaxEntryCountBE(keepBytes: number): Buffer {
  const buf = buildJpegWithOrientationBE(6).slice(); // mutable copy
  // ifd0 = 20; entry count field is at ifd0 = 20 (big-endian)
  buf.writeUInt16BE(0xffff, 20);
  return buf.subarray(0, keepBytes);
}

describe("readJpegExifOrientation — near-max IFD0 entry count (0xFFFF) safety", () => {
  // ---- (a) LE TIFF, count = 0xFFFF, buffer truncated so guard fires on i=0 ----
  //
  // keepBytes = 28 → buf.length = 28.
  // i=0: e = ifd0 + 2 + 0*12 = 22; e + 10 = 32; 32 >= 28 → break.
  // No entry is read; Orientation tag is never found → null.
  it("LE TIFF, count=0xFFFF, buffer truncated to 28 bytes: guard fires on first iteration, returns null without throwing", () => {
    const buf = buildJpegWithMaxEntryCountLE(28);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // ---- (a) BE TIFF, count = 0xFFFF, buffer truncated so guard fires on i=0 ----
  //
  // Identical logic with big-endian byte order.
  it("BE TIFF, count=0xFFFF, buffer truncated to 28 bytes: guard fires on first iteration, returns null without throwing", () => {
    const buf = buildJpegWithMaxEntryCountBE(28);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // ---- (b) LE TIFF, count = 0xFFFF, one non-Orientation entry, full buffer ----
  //
  // Full 40-byte buffer; count patched to 0xFFFF; entry tag changed from
  // 0x0112 (Orientation) to 0x010F (Make) so the loop skips it.
  // i=0: e = 22; e+10 = 32 < 40 → reads entry, tag ≠ 0x0112 → skip.
  // i=1: e = 34; e+10 = 44 >= 40 → break → null.
  it("LE TIFF, count=0xFFFF, non-Orientation tag, full 40-byte buffer: guard fires on second iteration, returns null without throwing", () => {
    const buf = buildJpegWithOrientation(6).slice();
    buf.writeUInt16LE(0xffff, 20); // patch count to 65535
    buf.writeUInt16LE(0x010f, 22); // patch tag: 0x0112 → 0x010F (Make)
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // ---- (b) BE TIFF, count = 0xFFFF, one non-Orientation entry, full buffer ----
  //
  // Same scenario with big-endian byte order.
  it("BE TIFF, count=0xFFFF, non-Orientation tag, full 40-byte buffer: guard fires on second iteration, returns null without throwing", () => {
    const buf = buildJpegWithOrientationBE(6).slice();
    buf.writeUInt16BE(0xffff, 20); // patch count to 65535
    buf.writeUInt16BE(0x010f, 22); // patch tag: 0x0112 → 0x010F (Make)
    expect(readJpegExifOrientation(buf)).toBeNull();
  });
});

// ---------------------------------------------------------------------------
// Suite 1f: Corrupt APP1 segment length (0xFFFF) safety.
//
// The segment walker advances `pos` by `2 + segLen` after each segment.  A
// corrupt or adversarially large segLen (0xFFFF = 65535, the maximum 16-bit
// value) causes the computed next-pos to leap far past buf.length.  The outer
// while condition
//   while (pos < buf.length - 3)
// must catch this without throwing a RangeError or reading undefined.
//
// Two sub-cases per TIFF byte-order variant (LE and BE):
//
//   (a) APP1 segment itself has segLen = 0xFFFF and the buffer is short
//       (10 bytes total).  `pos + 10 < buf.length` (2+10=12 < 10) is false
//       → the APP1 payload block is skipped entirely.  The walker then runs:
//         pos += 2 + 65535 = 65537
//       and the while guard `65537 < 10 − 3` fires → exits → null.
//
//   (b) A preceding dummy APP0 segment (FF E0) has segLen = 0xFFFF, followed
//       in the buffer by a valid APP1/EXIF segment that is never reached.
//       After the corrupt APP0 header at pos=2:
//         pos += 2 + 65535 = 65539  (buffer is ~42 bytes)
//       while guard fires → exits → null.
//
// Buffer layouts:
//
//   Case (a) — 10-byte truncated buffer:
//     0–1   SOI
//     2–3   APP1 marker (FF E1)
//     4–5   APP1 length = 0xFFFF  ← corrupt
//     6–9   partial payload (4 bytes, < the 6 bytes of "Exif\0\0")
//
//   Case (b) — valid LE/BE JPEG prepended with 4-byte corrupt APP0 header:
//     0–1   SOI
//     2–3   APP0 marker (FF E0)
//     4–5   APP0 length = 0xFFFF  ← corrupt
//     6–7   APP1 marker of the valid JPEG (= FF E1, never reached)
//     8+    valid APP1/EXIF payload
// ---------------------------------------------------------------------------

/**
 * Take a valid LE-TIFF minimal JPEG, corrupt its APP1 length field to 0xFFFF,
 * then slice to `keepBytes`.  With keepBytes=10 the `pos+10 < buf.length`
 * guard prevents entering the APP1 payload so the walker falls through to
 * `pos += 2 + 0xFFFF = 65537`, which the while condition catches.
 */
function buildJpegWithCorruptApp1SegLenLE(keepBytes: number): Buffer {
  const buf = buildJpegWithOrientation(6).slice(); // mutable copy
  // APP1 length field is at absolute offset 4 (pos=2 for APP1 marker + 2 for length).
  buf.writeUInt16BE(0xffff, 4);
  return buf.subarray(0, keepBytes);
}

/**
 * Big-endian counterpart of buildJpegWithCorruptApp1SegLenLE.
 */
function buildJpegWithCorruptApp1SegLenBE(keepBytes: number): Buffer {
  const buf = buildJpegWithOrientationBE(6).slice();
  buf.writeUInt16BE(0xffff, 4);
  return buf.subarray(0, keepBytes);
}

/**
 * Build a JPEG where a dummy APP0 segment preceding the valid APP1/EXIF block
 * has a corrupt segLen = 0xFFFF (LE TIFF variant).
 *
 * Layout:
 *   0–1   SOI
 *   2–3   APP0 marker (FF E0)
 *   4–5   APP0 length = 0xFFFF  ← corrupt
 *   6+    valid LE-TIFF APP1/EXIF + EOI (copied from buildJpegWithOrientation)
 *
 * After the walker reads APP0 at pos=2 with segLen=0xFFFF it sets
 * pos = 2 + 2 + 65535 = 65539, which is far past buf.length (~42 bytes).
 */
function buildJpegWithCorruptPrecedingSegLenLE(): Buffer {
  const validBuf = buildJpegWithOrientation(6); // 40-byte valid LE JPEG
  // SOI(2) + APP0 header(4) + rest of validBuf without its SOI(38) = 44 bytes
  const totalSize = 2 + 4 + (validBuf.length - 2);
  const buf = Buffer.alloc(totalSize, 0);
  let pos = 0;
  buf[pos++] = 0xff; buf[pos++] = 0xd8; // SOI
  buf[pos++] = 0xff; buf[pos++] = 0xe0; // APP0 marker
  buf.writeUInt16BE(0xffff, pos); pos += 2; // corrupt APP0 length
  validBuf.copy(buf, pos, 2); // paste APP1/EXIF + EOI (skip the original SOI)
  return buf;
}

/**
 * Big-endian counterpart of buildJpegWithCorruptPrecedingSegLenLE.
 * Uses a BE-TIFF APP1/EXIF block after the corrupt APP0 header.
 */
function buildJpegWithCorruptPrecedingSegLenBE(): Buffer {
  const validBuf = buildJpegWithOrientationBE(6); // 40-byte valid BE JPEG
  const totalSize = 2 + 4 + (validBuf.length - 2);
  const buf = Buffer.alloc(totalSize, 0);
  let pos = 0;
  buf[pos++] = 0xff; buf[pos++] = 0xd8; // SOI
  buf[pos++] = 0xff; buf[pos++] = 0xe0; // APP0 marker
  buf.writeUInt16BE(0xffff, pos); pos += 2; // corrupt APP0 length
  validBuf.copy(buf, pos, 2);
  return buf;
}

describe("readJpegExifOrientation — corrupt APP1 segment length (0xFFFF) safety", () => {
  // ---- (a) LE TIFF: APP1 itself has segLen = 0xFFFF, short 10-byte buffer -----
  //
  // buf.length = 10.
  // pos=2: while guard 2 < 10−3=7 → OK.
  // marker = 0xE1 (APP1); segLen = 0xFFFF.
  // `pos + 10 < buf.length` → 12 < 10 → false → skip APP1 payload block.
  // Not SOS; fall through to: pos += 2 + 65535 = 65537.
  // Next while: 65537 < 7 → false → exit → null.
  it("LE TIFF: APP1 segLen=0xFFFF, 10-byte buffer — walker overrun caught by while guard, returns null without throwing", () => {
    const buf = buildJpegWithCorruptApp1SegLenLE(10);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // ---- (a) BE TIFF: APP1 itself has segLen = 0xFFFF, short 10-byte buffer -----
  //
  // Identical logic with big-endian TIFF byte order in the (unreachable) payload.
  it("BE TIFF: APP1 segLen=0xFFFF, 10-byte buffer — walker overrun caught by while guard, returns null without throwing", () => {
    const buf = buildJpegWithCorruptApp1SegLenBE(10);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // ---- (b) LE TIFF: preceding APP0 has segLen = 0xFFFF -------------------
  //
  // buf.length ≈ 44 bytes (SOI + APP0 header + valid LE APP1/EXIF + EOI).
  // pos=2: marker=0xE0 (APP0, not APP1, not SOS); segLen=0xFFFF.
  // pos += 2 + 65535 = 65539; next while: 65539 < 41 → false → null.
  // The valid APP1/EXIF segment is never reached.
  it("LE TIFF: preceding APP0 segLen=0xFFFF — walker skips valid APP1/EXIF, returns null without throwing", () => {
    const buf = buildJpegWithCorruptPrecedingSegLenLE();
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // ---- (b) BE TIFF: preceding APP0 has segLen = 0xFFFF -------------------
  //
  // Same as the LE variant above, with a BE-TIFF APP1/EXIF payload that is
  // likewise never reached.
  it("BE TIFF: preceding APP0 segLen=0xFFFF — walker skips valid APP1/EXIF, returns null without throwing", () => {
    const buf = buildJpegWithCorruptPrecedingSegLenBE();
    expect(readJpegExifOrientation(buf)).toBeNull();
  });
});

// ---------------------------------------------------------------------------
// Suite 1g: Zero IFD0 entry count (count = 0) safety.
//
// An IFD0 entry count of 0 is valid per the EXIF/TIFF spec — it means the IFD
// exists but carries no tags.  The for-loop body is never entered, so the
// Orientation tag is never found and readJpegExifOrientation must return null
// cleanly without throwing.  This pins the lower boundary of the uint16 count
// range (complement to the 0xFFFF upper-boundary tests in Suite 1e).
//
// Buffer layout (40 bytes, absolute offsets — identical to Suite 1e):
//   0–1   SOI
//   2–3   APP1 marker
//   4–5   APP1 length (= 34)
//   6–11  "Exif\0\0"
//   12–13 TIFF byte-order mark ('I','I' or 'M','M')  ← t = 12
//   14–15 TIFF magic = 42
//   16–19 IFD0 offset = 8 → ifd0 = t + 8 = 20
//   20–21 IFD0 entry count  ← overwritten with 0x0000
//   22–33 12-byte IFD0 entry  (present in the buffer, but never walked)
//   34–37 next-IFD pointer = 0
//   38–39 EOI
// ---------------------------------------------------------------------------

/**
 * Build a minimal LE-TIFF JPEG and overwrite the IFD0 entry count with 0.
 * The rest of the buffer (including the entry slot) is unchanged; the loop
 * simply never executes.
 */
function buildJpegWithZeroEntryCountLE(): Buffer {
  const buf = buildJpegWithOrientation(6).slice(); // mutable copy
  // ifd0 = 20; entry count field at absolute offset 20 (little-endian)
  buf.writeUInt16LE(0, 20);
  return buf;
}

/**
 * Build a minimal BE-TIFF JPEG and overwrite the IFD0 entry count with 0.
 */
function buildJpegWithZeroEntryCountBE(): Buffer {
  const buf = buildJpegWithOrientationBE(6).slice(); // mutable copy
  // ifd0 = 20; entry count field at absolute offset 20 (big-endian)
  buf.writeUInt16BE(0, 20);
  return buf;
}

describe("readJpegExifOrientation — zero IFD0 entry count safety", () => {
  // ---- LE TIFF, count = 0 -------------------------------------------------
  //
  // The for-loop condition `i < 0` is immediately false; no entry is read.
  // Orientation tag is never encountered → must return null without throwing.
  it("LE TIFF, count=0: loop body is never entered, returns null without throwing", () => {
    const buf = buildJpegWithZeroEntryCountLE();
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // ---- BE TIFF, count = 0 -------------------------------------------------
  //
  // Identical semantics with big-endian byte order.
  it("BE TIFF, count=0: loop body is never entered, returns null without throwing", () => {
    const buf = buildJpegWithZeroEntryCountBE();
    expect(readJpegExifOrientation(buf)).toBeNull();
  });
});

// ---------------------------------------------------------------------------
// Suite 2: Synthetic multi-entry EXIF fixtures.
//
// Generated by server/__fixtures__/generate-fixtures.cjs — realistic EXIF
// segments with Make, Model, Orientation, XResolution, YResolution, and
// ResolutionUnit entries matching the structure real phones write.
//
// iPhone-style fixtures use little-endian ('II') TIFF byte order.
// Android-style fixtures use big-endian ('MM') TIFF byte order.
// ---------------------------------------------------------------------------

describe("readJpegExifOrientation — synthetic multi-entry EXIF (LE + BE layouts)", () => {
  // ---- iPhone-style (little-endian TIFF) ----------------------------------

  it("LE TIFF portrait (orientation=6): returns 6 — sideways candidate", () => {
    // Mirrors a photo taken in portrait mode on an iPhone; stored 90° CW.
    expect(readJpegExifOrientation(fixture("iphone_portrait_o6.jpg"))).toBe(6);
  });

  it("LE TIFF upright (orientation=1): returns 1 — must NOT be a candidate", () => {
    // Landscape shot or a photo already re-encoded upright; should be skipped.
    expect(readJpegExifOrientation(fixture("iphone_upright_o1.jpg"))).toBe(1);
  });

  // ---- Android-style (big-endian / Motorola-byte-order TIFF) -------------

  it("BE TIFF portrait (orientation=6): returns 6 — sideways candidate", () => {
    // Many Android OEMs write big-endian ('MM') TIFF headers.
    expect(readJpegExifOrientation(fixture("android_portrait_o6_be.jpg"))).toBe(6);
  });

  it("BE TIFF upright (orientation=1): returns 1 — must NOT be a candidate", () => {
    expect(readJpegExifOrientation(fixture("android_upright_o1_be.jpg"))).toBe(1);
  });

  it("BE TIFF 90° CCW (orientation=8): returns 8 — sideways candidate", () => {
    // Orientation=8 occurs when a phone is rotated the opposite direction.
    expect(readJpegExifOrientation(fixture("android_sideways_o8_be.jpg"))).toBe(8);
  });
});

// ---------------------------------------------------------------------------
// Suite 3: Real unmodified device JPEGs — provenance documented below.
//
// Every file was fetched verbatim from a public open-source fixture repository
// and its orientation was independently verified with `file` (libmagic EXIF
// decoder) before being hard-coded into a test expectation.
//
// The three files that are header-trimmed (iphone4s_o6, iphone5_o3,
// samsung_galaxysii_o6) had their scan payload (everything from the SOS marker
// onwards) removed to keep the committed file small; the EXIF APP1 segment
// that readJpegExifOrientation reads is byte-for-byte identical to the original.
//
// File inventory (all in server/__fixtures__/real/):
//
//   iphone4s_o6.jpg
//       Source  : github.com/drewnoakes/metadata-extractor-images,
//                 jpg/Apple iPhone 4S.jpg (widely-used real-device EXIF test suite)
//       Device  : Apple iPhone 4S (iOS 5.1.1)
//       TIFF BO : big-endian ('MM')   IFD0 entries: 10
//       Orientation: 6 (upper-right — 90° CW, the canonical iPhone portrait)
//       file(1) : TIFF image data, big-endian, direntries=10,
//                 manufacturer=Apple, model=iPhone 4S, orientation=upper-right
//       Note    : Trimmed at SOS marker; original = 3.8 MB; trimmed = 1.3 KB
//
//   iphone5_o3.jpg
//       Source  : github.com/drewnoakes/metadata-extractor-images,
//                 jpg/Apple iPhone 5.jpg
//       Device  : Apple iPhone 5
//       TIFF BO : big-endian ('MM')   IFD0 entries: 11 (includes GPS sub-IFD)
//       Orientation: 3 (lower-right — 180° rotation; a second non-upright value)
//       file(1) : TIFF image data, big-endian, direntries=11,
//                 manufacturer=Apple, model=iPhone 5, orientation=lower-right,
//                 GPS-Data
//       Note    : Trimmed at SOS marker; original = 2.3 MB; trimmed = 1.5 KB
//
//   samsung_galaxysii_o6.jpg
//       Source  : github.com/drewnoakes/metadata-extractor-images,
//                 jpg/Samsung GT-I9100 (Galaxy SII).jpg
//       Device  : Samsung Galaxy SII (Android)
//       TIFF BO : little-endian ('II')   IFD0 entries: 12
//       Orientation: 6 (upper-right — 90° CW portrait, same as the iPhone case)
//       file(1) : TIFF image data, little-endian, direntries=12,
//                 manufacturer=SAMSUNG, model=GT-I9100, orientation=upper-right
//       Note    : Trimmed at SOS marker; original = 3.2 MB; trimmed = 1.5 KB
//       Significance: LE TIFF byte order + non-1 orientation from a real Android
//                 phone — the specific combination that is hardest to synthesise.
//
//   canon_o1.jpg
//       Source  : github.com/recurser/exif-orientation-examples, Landscape_1.jpg
//       Device  : Canon camera (used as a compact real-BE-TIFF baseline)
//       TIFF BO : big-endian ('MM')   IFD0 entries: 5
//       Orientation: 1 (upper-left, upright)
//       file(1) : TIFF image data, big-endian, direntries=5, orientation=upper-left
//
//   canon_portrait_o6.jpg
//       Source  : github.com/recurser/exif-orientation-examples, Portrait_6.jpg
//       Device  : Canon camera
//       TIFF BO : big-endian ('MM')   IFD0 entries: 5
//       Orientation: 6 (upper-right, 90° CW)
//       file(1) : TIFF image data, big-endian, direntries=5, orientation=upper-right
//
//   canon_o8.jpg
//       Source  : github.com/recurser/exif-orientation-examples, Landscape_8.jpg
//       Device  : Canon camera
//       TIFF BO : big-endian ('MM')   IFD0 entries: 5
//       Orientation: 8 (lower-left, 90° CCW)
//       file(1) : TIFF image data, big-endian, direntries=5, orientation=lower-left
//
//   pixel_portrait.jpg
//       Source  : github.com/MikeKovarik/exifr, IMG_20180725_163423.jpg
//       Device  : Google Pixel (Android phone)
//       TIFF BO : little-endian ('II')   IFD0 entries: 13 (includes GPS sub-IFD)
//       Orientation: 1 (upper-left, landscape orientation)
//       file(1) : TIFF image data, little-endian, direntries=13, GPS-Data,
//                 manufacturer=Google, model=Pixel
//       Note    : Trimmed at SOS marker; EXIF segment intact and unchanged.
//
//   cam_Samsung_Digimax_i50_MP3.jpg
//       Source  : github.com/ianare/exif-samples, Samsung_Digimax_i50_MP3.jpg
//       Device  : Samsung Digimax i50 MP3 consumer camera
//       TIFF BO : little-endian ('II')   IFD0 entries: 12
//       Orientation: 1 (upper-left, landscape)
//       file(1) : TIFF image data, little-endian, direntries=12,
//                 manufacturer=Samsung Techwin, model=Digimax i50 MP3
// ---------------------------------------------------------------------------

describe("readJpegExifOrientation — real unmodified device JPEGs", () => {
  // ---- Real Apple iPhone photos -------------------------------------------

  it("iPhone 4S (BE TIFF, o=6): returns 6 — real iPhone portrait, sideways candidate", () => {
    // Apple iPhone 4S.jpg from drewnoakes/metadata-extractor-images.
    // Make=Apple, Model=iPhone 4S, iOS 5.1.1. Orientation=6 (upper-right)
    // is the canonical portrait orientation for iPhones held normally.
    // `file` confirms: TIFF big-endian, direntries=10, orientation=upper-right.
    expect(readJpegExifOrientation(fixture("real/iphone4s_o6.jpg"))).toBe(6);
  });

  it("iPhone 5 (BE TIFF, o=3): returns 3 — real iPhone rotated 180°, sideways candidate", () => {
    // Apple iPhone 5.jpg from drewnoakes/metadata-extractor-images.
    // Make=Apple, Model=iPhone 5. Orientation=3 (lower-right, 180° rotation).
    // 11 IFD0 entries including GPS sub-IFD pointer.
    // `file` confirms: TIFF big-endian, direntries=11, orientation=lower-right.
    expect(readJpegExifOrientation(fixture("real/iphone5_o3.jpg"))).toBe(3);
  });

  // ---- Real Android phone photos (LE TIFF + non-1 orientation) ------------

  it("Samsung Galaxy SII Android (LE TIFF, o=6): returns 6 — real Android portrait, sideways candidate", () => {
    // Samsung GT-I9100 (Galaxy SII).jpg from drewnoakes/metadata-extractor-images.
    // Make=SAMSUNG, Model=GT-I9100, software=I9100XWLPT. LE TIFF byte order
    // ('II') — same byte order used by modern Android phones and iPhones.
    // Orientation=6 (upper-right, 90° CW portrait). 12 IFD0 entries.
    // `file` confirms: TIFF little-endian, direntries=12, orientation=upper-right.
    expect(readJpegExifOrientation(fixture("real/samsung_galaxysii_o6.jpg"))).toBe(6);
  });

  it("Google Pixel Android (LE TIFF, 13-entry IFD0 + GPS, o=1): returns 1 — upright", () => {
    // IMG_20180725_163423.jpg from MikeKovarik/exifr test fixtures.
    // Make=Google, Model=Pixel. LE TIFF, 13 IFD entries including GPS sub-IFD.
    // Orientation=1 (landscape shot, upright). Proves the LE path iterates a
    // large IFD correctly before hitting the Orientation tag.
    expect(readJpegExifOrientation(fixture("real/pixel_portrait.jpg"))).toBe(1);
  });

  // ---- Canon camera real images (BE TIFF baseline) -----------------------

  it("Canon (BE TIFF, o=1): returns 1 — upright, must NOT be a candidate", () => {
    // Landscape_1.jpg from recurser/exif-orientation-examples.
    expect(readJpegExifOrientation(fixture("real/canon_o1.jpg"))).toBe(1);
  });

  it("Canon (BE TIFF, o=6): returns 6 — BE sideways candidate, 90° CW portrait", () => {
    // Portrait_6.jpg from recurser/exif-orientation-examples (252 KB).
    expect(readJpegExifOrientation(fixture("real/canon_portrait_o6.jpg"))).toBe(6);
  });

  it("Canon (BE TIFF, o=8): returns 8 — BE sideways candidate, 90° CCW portrait", () => {
    // Landscape_8.jpg from recurser/exif-orientation-examples.
    expect(readJpegExifOrientation(fixture("real/canon_o8.jpg"))).toBe(8);
  });

  // ---- Real Samsung consumer camera (LE TIFF, 12 entries, o=1) -----------

  it("Samsung Digimax (LE TIFF, 12-entry IFD0, o=1): returns 1 — upright", () => {
    // Samsung_Digimax_i50_MP3.jpg from ianare/exif-samples. LE TIFF, 12 IFD
    // entries (Make, Model, Orientation, XResolution, YResolution, Software,
    // DateTime, Copyright, and more) — iterates many entries to find Orientation.
    expect(readJpegExifOrientation(fixture("real/cam_Samsung_Digimax_i50_MP3.jpg"))).toBe(1);
  });
});

// ---------------------------------------------------------------------------
// Consolidated malformed-input suite: corrupt segment lengths, bad byte-order
// marks, degenerate IFD entry counts, and exact buffer-boundary cases. Every
// case must return null quickly (no throw, no hang, no out-of-bounds read).
// ---------------------------------------------------------------------------
describe("readJpegExifOrientation — malformed input hardening", () => {
  /** Minimal valid JPEG (SOI + APP1 EXIF w/ orientation 6 + EOI) to mutate. */
  function validJpeg(): Buffer {
    const buf = Buffer.alloc(40, 0);
    let p = 0;
    buf[p++] = 0xff; buf[p++] = 0xd8;             // SOI
    buf[p++] = 0xff; buf[p++] = 0xe1;             // APP1
    buf.writeUInt16BE(34, p); p += 2;             // segLen = 2 + 32
    buf.write("Exif\0\0", p, "latin1"); p += 6;
    const t = p;                                   // TIFF header
    buf.write("II", t, "latin1");
    buf.writeUInt16LE(42, t + 2);
    buf.writeUInt32LE(8, t + 4);                   // IFD0 offset
    const ifd0 = t + 8;
    buf.writeUInt16LE(1, ifd0);                    // 1 entry
    const e = ifd0 + 2;
    buf.writeUInt16LE(0x0112, e);                  // Orientation tag
    buf.writeUInt16LE(3, e + 2);                   // type SHORT
    buf.writeUInt32LE(1, e + 4);                   // count
    buf.writeUInt16LE(6, e + 8);                   // value = 6
    buf.writeUInt32LE(0, ifd0 + 2 + 12);           // next-IFD = none
    buf[38] = 0xff; buf[39] = 0xd9;                // EOI
    return buf;
  }

  it("sanity: the unmutated builder JPEG parses to orientation 6", () => {
    expect(readJpegExifOrientation(validJpeg())).toBe(6);
  });

  // ---- segment length corruption ----
  it("segment length 0: returns null without hanging", () => {
    const buf = validJpeg();
    buf.writeUInt16BE(0, 4); // APP1 length field
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  it("segment length 1 (below the 2-byte minimum): returns null without hanging", () => {
    const buf = validJpeg();
    buf.writeUInt16BE(1, 4);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  it("APP1 length claiming to extend past the end of the buffer: bounded parse, no out-of-bounds read", () => {
    // Contract: the walker must never read beyond the buffer, but a truncated
    // (or length-corrupted) APP1 whose TIFF header is still intact SHOULD
    // yield its orientation — real camera files trimmed mid-segment depend on
    // this. The oversized length only stops the walk after this segment.
    const buf = validJpeg();
    buf.writeUInt16BE(0xfff0, 4); // far beyond the 40-byte buffer
    expect(readJpegExifOrientation(buf)).toBe(6);
    // Same corruption with the TIFF header ALSO truncated: null, no throw.
    const cut = buf.subarray(0, 16); // ends inside the TIFF header
    expect(readJpegExifOrientation(cut)).toBeNull();
  });

  it("non-EXIF segment with length 0 before a valid APP1: stops instead of looping forever", () => {
    // SOI + APP0 with segLen 0 (would never advance under naive parsing).
    const head = Buffer.from([0xff, 0xd8, 0xff, 0xe0, 0x00, 0x00]);
    const buf = Buffer.concat([head, validJpeg().subarray(2)]);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // ---- byte-order mark corruption ----
  for (const [label, b0, b1] of [
    ["mixed 'IM'", 0x49, 0x4d],
    ["mixed 'MI'", 0x4d, 0x49],
    ["zero-filled BOM", 0x00, 0x00],
    ["'MM' first byte only ('M\\0')", 0x4d, 0x00],
  ] as const) {
    it(`mismatched byte-order mark (${label}): returns null, never garbage`, () => {
      const buf = validJpeg();
      buf[12] = b0; buf[13] = b1; // TIFF BOM (TIFF header starts at offset 12)
      expect(readJpegExifOrientation(buf)).toBeNull();
    });
  }

  // ---- degenerate IFD entry counts ----
  it("zero IFD0 entry count: returns null without walking into garbage", () => {
    const buf = validJpeg();
    buf.writeUInt16LE(0, 20); // IFD0 count at TIFF(12)+8 = abs offset 20
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  it("IFD0 count of 1 with the buffer ending exactly at the last byte of the entry: still parses", () => {
    // Truncate right after the single 12-byte entry (drop next-IFD ptr + EOI).
    const buf = validJpeg().subarray(0, 34); // entry occupies 22..33
    expect(readJpegExifOrientation(buf)).toBe(6);
  });

  it("IFD0 count of 1 with the buffer truncated one byte INTO the entry's value: returns null or a bounded read, never throws", () => {
    const buf = validJpeg().subarray(0, 31); // cuts inside the entry's value field
    expect(() => readJpegExifOrientation(buf)).not.toThrow();
  });

  it("huge IFD0 entry count with tiny buffer: bounded scan, returns null fast", () => {
    const buf = validJpeg();
    buf.writeUInt16LE(0xffff, 20);
    buf.writeUInt16LE(0x9999, 22); // destroy the orientation tag id
    const started = Date.now();
    expect(readJpegExifOrientation(buf)).toBeNull();
    expect(Date.now() - started).toBeLessThan(1000);
  });
});

// ---------------------------------------------------------------------------
// Suite 1h: Zero-length and one-length non-APP1 segment guard after APP1/EXIF.
//
// The segment walker advances `pos` by `2 + segLen` after processing each
// segment.  The JPEG spec requires the 2-byte length field to be at least 2
// (it counts itself).  A corrupt or truncated file can produce a non-APP1
// segment (e.g. APP2 = FF E2) with segLen = 0 or segLen = 1, either of which
// would leave `pos` pointing back at the same segment (segLen 0: pos += 2,
// re-reads the same marker bytes; segLen 1: pos += 3, lands in the length
// field of the same segment), creating an infinite loop.
//
// The guard in photoExif.ts:
//   if (segLen < 2) break;
// fires before the advance and stops the walk immediately.
//
// These tests exercise the guard via a buffer that has a valid APP1/EXIF
// segment first (with zero IFD0 entries, so no Orientation tag is found and
// the walker advances past APP1), immediately followed by a non-APP1 APP2
// segment carrying the corrupt length.  Both LE ('II') and BE ('MM') TIFF
// variants of the APP1 header are covered.
//
// Buffer layout (32 bytes total, all offsets absolute):
//   0–1   SOI
//   2–3   APP1 marker (FF E1)
//   4–5   APP1 segLen = 22 (2 + 20-byte EXIF payload)
//   6–11  "Exif\0\0"
//   12–13 TIFF byte-order mark ('I','I' or 'M','M')  ← t = 12
//   14–15 TIFF magic = 42
//   16–19 IFD0 offset = 8 → ifd0 = t + 8 = 20
//   20–21 IFD0 entry count = 0  (no entries, so Orientation not found)
//   22–25 next-IFD pointer = 0
//          (walker advances: pos = 2 + 2 + 22 = 26)
//   26–27 APP2 marker (FF E2)  ← next segment, walker sees this
//   28–29 APP2 segLen = 0 or 1  ← corrupt; guard fires here
//   30–31 EOI
//
// With segLen = 0: naive pos += 2 + 0 = 2 would re-point at 0xFF of APP2,
//   infinite loop.  Guard breaks instead.
// With segLen = 1: naive pos += 2 + 1 = 3 would land at 0xE2 of APP2 (the
//   second byte of the marker), misaligning the walk.  Guard breaks instead.
// ---------------------------------------------------------------------------

/**
 * Build a 32-byte JPEG with:
 *   - an APP1/EXIF segment using LE ('II') TIFF with zero IFD0 entries
 *     (no Orientation tag → walker continues past APP1)
 *   - followed by an APP2 segment whose length field is set to `badSegLen`
 *   - followed by EOI
 *
 * The corrupt APP2 segLen triggers the `if (segLen < 2) break` guard.
 */
function buildJpegWithBadFollowingSegLenLE(badSegLen: number): Buffer {
  // APP1 EXIF payload: "Exif\0\0"(6) + TIFF-header(8) + IFD0-count(2) + next-IFD(4) = 20
  const exifPayload = 20;
  const app1SegLen = 2 + exifPayload; // 22 (includes the length field itself)

  // Total: SOI(2) + APP1-marker(2) + APP1-segLen-field(2) + exifPayload(20)
  //        + APP2-marker(2) + APP2-segLen-field(2) + EOI(2) = 32
  const totalSize = 2 + 2 + 2 + exifPayload + 2 + 2 + 2;
  const buf = Buffer.alloc(totalSize, 0);
  let pos = 0;

  // SOI
  buf[pos++] = 0xff; buf[pos++] = 0xd8;

  // APP1 marker
  buf[pos++] = 0xff; buf[pos++] = 0xe1;
  buf.writeUInt16BE(app1SegLen, pos); pos += 2;

  // "Exif\0\0"
  buf.write("Exif\0\0", pos, "latin1"); pos += 6;

  // TIFF header — little-endian ('II')
  buf[pos++] = 0x49; buf[pos++] = 0x49; // 'I','I'
  buf.writeUInt16LE(42, pos); pos += 2;  // magic = 42
  buf.writeUInt32LE(8, pos); pos += 4;   // IFD0 offset = 8 from TIFF base

  // IFD0: entry count = 0, next-IFD = 0
  buf.writeUInt16LE(0, pos); pos += 2;
  buf.writeUInt32LE(0, pos); pos += 4;

  // Walker should now be at pos=26 after advancing 2 + app1SegLen = 26.
  // APP2 segment with corrupt length.
  buf[pos++] = 0xff; buf[pos++] = 0xe2; // APP2 marker
  buf.writeUInt16BE(badSegLen, pos); pos += 2;

  // EOI
  buf[pos++] = 0xff; buf[pos++] = 0xd9;

  if (pos !== totalSize) {
    throw new Error(`Layout error: wrote ${pos} bytes, expected ${totalSize}`);
  }
  return buf;
}

/**
 * Big-endian ('MM') counterpart of buildJpegWithBadFollowingSegLenLE.
 * The APP1/EXIF uses BE TIFF byte order; everything else is identical.
 */
function buildJpegWithBadFollowingSegLenBE(badSegLen: number): Buffer {
  const exifPayload = 20;
  const app1SegLen = 2 + exifPayload; // 22

  const totalSize = 2 + 2 + 2 + exifPayload + 2 + 2 + 2;
  const buf = Buffer.alloc(totalSize, 0);
  let pos = 0;

  // SOI
  buf[pos++] = 0xff; buf[pos++] = 0xd8;

  // APP1 marker
  buf[pos++] = 0xff; buf[pos++] = 0xe1;
  buf.writeUInt16BE(app1SegLen, pos); pos += 2;

  // "Exif\0\0"
  buf.write("Exif\0\0", pos, "latin1"); pos += 6;

  // TIFF header — big-endian ('MM')
  buf[pos++] = 0x4d; buf[pos++] = 0x4d; // 'M','M'
  buf.writeUInt16BE(42, pos); pos += 2;  // magic = 42
  buf.writeUInt32BE(8, pos); pos += 4;   // IFD0 offset = 8 from TIFF base

  // IFD0: entry count = 0, next-IFD = 0
  buf.writeUInt16BE(0, pos); pos += 2;
  buf.writeUInt32BE(0, pos); pos += 4;

  // APP2 segment with corrupt length.
  buf[pos++] = 0xff; buf[pos++] = 0xe2; // APP2 marker
  buf.writeUInt16BE(badSegLen, pos); pos += 2;

  // EOI
  buf[pos++] = 0xff; buf[pos++] = 0xd9;

  if (pos !== totalSize) {
    throw new Error(`Layout error: wrote ${pos} bytes, expected ${totalSize}`);
  }
  return buf;
}

describe("readJpegExifOrientation — zero/one-length non-APP1 segment after APP1/EXIF", () => {
  // ---- LE TIFF ('II') APP1/EXIF followed by APP2 with segLen = 0 ----------
  //
  // Walker parses APP1 (no Orientation tag found), advances pos to 26.
  // At pos=26: marker=0xE2 (APP2, not APP1, not SOS); segLen=0.
  // `if (segLen < 2) break` fires → walker exits → returns null.
  // Without the guard: pos += 2 + 0 = 26, re-reads 0xFF at pos=26, infinite loop.
  it("LE TIFF: APP2 with segLen=0 after APP1/EXIF — guard fires, returns null without hanging", () => {
    const buf = buildJpegWithBadFollowingSegLenLE(0);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // ---- LE TIFF ('II') APP1/EXIF followed by APP2 with segLen = 1 ----------
  //
  // Same path; segLen=1 is also below the minimum of 2.
  // `if (segLen < 2) break` fires → returns null.
  // Without the guard: pos += 2 + 1 = 29, misaligns the walk onto 0xE2 (APP2
  // second byte), corrupting all subsequent marker reads.
  it("LE TIFF: APP2 with segLen=1 after APP1/EXIF — guard fires, returns null without hanging", () => {
    const buf = buildJpegWithBadFollowingSegLenLE(1);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // ---- BE TIFF ('MM') APP1/EXIF followed by APP2 with segLen = 0 ----------
  //
  // Same scenario with a big-endian TIFF header in the APP1 block.
  // The BE code path is exercised; the guard at `if (segLen < 2) break`
  // fires identically regardless of TIFF byte order.
  it("BE TIFF: APP2 with segLen=0 after APP1/EXIF — guard fires, returns null without hanging", () => {
    const buf = buildJpegWithBadFollowingSegLenBE(0);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // ---- BE TIFF ('MM') APP1/EXIF followed by APP2 with segLen = 1 ----------
  it("BE TIFF: APP2 with segLen=1 after APP1/EXIF — guard fires, returns null without hanging", () => {
    const buf = buildJpegWithBadFollowingSegLenBE(1);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });
});
