// @vitest-environment node
//
// Unit tests for readJpegExifOrientation — the pure-JS EXIF orientation reader
// used by the sideways-photo detector.
//
// Two suites:
//  1. Synthetic buffers — built in memory to pin exact byte-level behaviour.
//  2. Fixture files    — realistic multi-entry EXIF JPEGs generated by
//     server/__fixtures__/generate-fixtures.cjs to mirror the layouts
//     that iPhone (little-endian TIFF) and Android (big-endian TIFF) cameras
//     produce in the field.
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { readJpegExifOrientation } from "./photoExif";

function fixture(name: string): Buffer {
  return readFileSync(join(__dirname, "__fixtures__", name));
}

// ---------------------------------------------------------------------------
// Helpers: build minimal synthetic JPEG buffers with a real APP1/EXIF segment.
// ---------------------------------------------------------------------------

/**
 * Write a 2-byte big-endian unsigned integer into buf at offset.
 */
function writeU16BE(buf: Buffer, offset: number, value: number) {
  buf[offset] = (value >> 8) & 0xff;
  buf[offset + 1] = value & 0xff;
}

/**
 * Write a 4-byte little-endian unsigned integer into buf at offset.
 */
function writeU32LE(buf: Buffer, offset: number, value: number) {
  buf.writeUInt32LE(value, offset);
}

/**
 * Write a 2-byte little-endian unsigned integer into buf at offset.
 */
function writeU16LE(buf: Buffer, offset: number, value: number) {
  buf.writeUInt16LE(value, offset);
}

/**
 * Write a 4-byte big-endian unsigned integer into buf at offset.
 */
function writeU32BE(buf: Buffer, offset: number, value: number) {
  buf.writeUInt32BE(value, offset);
}

/**
 * Build a minimal JPEG with a single APP1/EXIF segment containing one IFD0
 * entry: the Orientation tag (0x0112) set to `orientation`.
 *
 * Layout (little-endian TIFF):
 *   SOI (2) | APP1 marker (2) | APP1 length (2) | "Exif\0\0" (6)
 *   TIFF header: byte-order (2) + magic 42 (2) + IFD0 offset (4) = 8
 *   IFD0: entry count (2) + one 12-byte entry + next-IFD ptr (4)
 *   Entry: tag (2) + type SHORT (2) + count 1 (4) + value (2) + pad (2)
 */
function buildJpegWithOrientation(orientation: number): Buffer {
  // Sizes (all at TIFF-relative offsets):
  //   TIFF header = 8 bytes, IFD0 starts right after → offset 8
  //   IFD0 = 2 (count) + 12 (one entry) + 4 (next IFD) = 18 bytes
  const tiffSize = 8 + 18; // 26 bytes

  // APP1 payload = "Exif\0\0" (6) + TIFF (26) = 32 bytes
  // APP1 segment length field (big-endian) includes the 2-byte length field itself
  // so segLen = 2 + 32 = 34, but the actual bytes written after the length field
  // are 32. The length field value (per JFIF spec) = payload + 2 = 34.
  const exifPayloadSize = 6 + tiffSize; // 32
  const app1SegLen = 2 + exifPayloadSize; // 34 (length field value)

  // Total buffer: SOI(2) + APP1marker(2) + lenField(2) + exifPayload(32) + EOI(2) = 40
  const totalSize = 2 + 2 + 2 + exifPayloadSize + 2;
  const buf = Buffer.alloc(totalSize, 0);

  let pos = 0;

  // SOI
  buf[pos++] = 0xff;
  buf[pos++] = 0xd8;

  // APP1 marker
  buf[pos++] = 0xff;
  buf[pos++] = 0xe1;

  // APP1 segment length (big-endian, includes the 2-byte length field)
  writeU16BE(buf, pos, app1SegLen);
  pos += 2;

  // "Exif\0\0"
  buf.write("Exif\0\0", pos, "latin1");
  pos += 6;

  // TIFF header (little-endian: 'II')
  const tiffBase = pos;
  buf[pos++] = 0x49; // 'I'
  buf[pos++] = 0x49; // 'I'
  writeU16LE(buf, pos, 42); // TIFF magic
  pos += 2;
  writeU32LE(buf, pos, 8); // IFD0 offset from TIFF header start = 8
  pos += 4;

  // IFD0 (starts at tiffBase + 8)
  writeU16LE(buf, pos, 1); // entry count = 1
  pos += 2;

  // IFD0 entry: Orientation tag
  writeU16LE(buf, pos, 0x0112); // tag = Orientation
  pos += 2;
  writeU16LE(buf, pos, 3); // type = SHORT
  pos += 2;
  writeU32LE(buf, pos, 1); // count = 1
  pos += 4;
  writeU16LE(buf, pos, orientation); // value
  pos += 2;
  writeU16LE(buf, pos, 0); // padding (value offset is 4 bytes; SHORT is 2, pad with 0)
  pos += 2;

  // next IFD pointer = 0 (no more IFDs)
  writeU32LE(buf, pos, 0);
  pos += 4;

  // EOI
  buf[pos++] = 0xff;
  buf[pos++] = 0xd9;

  // Verify our layout math is correct
  if (pos !== totalSize) {
    throw new Error(`Layout error: wrote ${pos} bytes, expected ${totalSize}`);
  }

  // Sanity check: TIFF IFD0 address
  void tiffBase;

  return buf;
}

/**
 * Build a minimal JPEG with a single APP1/EXIF segment containing one IFD0
 * entry: the Orientation tag (0x0112) set to `orientation`.
 *
 * This is the big-endian ('MM') counterpart of buildJpegWithOrientation.
 *
 * Layout (big-endian TIFF):
 *   SOI (2) | APP1 marker (2) | APP1 length (2) | "Exif\0\0" (6)
 *   TIFF header: byte-order 'MM' (2) + magic 42 BE (2) + IFD0 offset BE (4) = 8
 *   IFD0: entry count BE (2) + one 12-byte entry + next-IFD ptr BE (4)
 *   Entry: tag BE (2) + type SHORT BE (2) + count BE (4) + value BE (2) + pad (2)
 */
function buildJpegWithOrientationBE(orientation: number): Buffer {
  const tiffSize = 8 + 18; // 26 bytes (same layout as LE version)
  const exifPayloadSize = 6 + tiffSize; // 32
  const app1SegLen = 2 + exifPayloadSize; // 34

  const totalSize = 2 + 2 + 2 + exifPayloadSize + 2;
  const buf = Buffer.alloc(totalSize, 0);

  let pos = 0;

  // SOI
  buf[pos++] = 0xff;
  buf[pos++] = 0xd8;

  // APP1 marker
  buf[pos++] = 0xff;
  buf[pos++] = 0xe1;

  // APP1 segment length (big-endian)
  writeU16BE(buf, pos, app1SegLen);
  pos += 2;

  // "Exif\0\0"
  buf.write("Exif\0\0", pos, "latin1");
  pos += 6;

  // TIFF header (big-endian: 'MM')
  buf[pos++] = 0x4d; // 'M'
  buf[pos++] = 0x4d; // 'M'
  writeU16BE(buf, pos, 42); // TIFF magic (big-endian)
  pos += 2;
  writeU32BE(buf, pos, 8); // IFD0 offset from TIFF header start = 8
  pos += 4;

  // IFD0 (starts at TIFF base + 8)
  writeU16BE(buf, pos, 1); // entry count = 1
  pos += 2;

  // IFD0 entry: Orientation tag (all fields big-endian)
  writeU16BE(buf, pos, 0x0112); // tag = Orientation
  pos += 2;
  writeU16BE(buf, pos, 3); // type = SHORT
  pos += 2;
  writeU32BE(buf, pos, 1); // count = 1
  pos += 4;
  writeU16BE(buf, pos, orientation); // value (first 2 bytes of the 4-byte value field)
  pos += 2;
  writeU16BE(buf, pos, 0); // padding
  pos += 2;

  // next IFD pointer = 0 (no more IFDs)
  writeU32BE(buf, pos, 0);
  pos += 4;

  // EOI
  buf[pos++] = 0xff;
  buf[pos++] = 0xd9;

  if (pos !== totalSize) {
    throw new Error(`Layout error: wrote ${pos} bytes, expected ${totalSize}`);
  }

  return buf;
}

/**
 * Build a minimal JPEG with no APP1 segment (just SOI + EOI).
 */
function buildJpegNoExif(): Buffer {
  return Buffer.from([0xff, 0xd8, 0xff, 0xd9]);
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("readJpegExifOrientation — synthetic single-entry buffers", () => {
  it("returns 6 for a JPEG with Orientation=6 (90° CW — most common iPhone portrait)", () => {
    const buf = buildJpegWithOrientation(6);
    expect(readJpegExifOrientation(buf)).toBe(6);
  });

  it("returns 1 for a JPEG with Orientation=1 (upright — must not appear in candidates)", () => {
    const buf = buildJpegWithOrientation(1);
    expect(readJpegExifOrientation(buf)).toBe(1);
  });

  it("returns null for a JPEG with no EXIF segment", () => {
    const buf = buildJpegNoExif();
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // Reload-safety invariant: canvas.toDataURL('image/jpeg') produces a JPEG
  // with no EXIF APP1 segment. After runFleetFix / runPhotoFix re-uploads a
  // photo via the canvas path, the stored bytes look like buildJpegNoExif().
  // The scan filter is `orientation !== null && orientation !== 1`. Because
  // null is excluded by that test, fixed photos never reappear as candidates
  // in a fresh scan after a page reload — no client-side "fixed IDs" set is
  // needed to prevent double-fixing.
  it("canvas-fixed photo (no EXIF) is excluded from scan candidates on reload", () => {
    // Simulate the bytes stored after orientedJpegDataUrl() re-upload:
    // a plain JPEG with no APP1/EXIF block.
    const fixedBuf = buildJpegNoExif();
    const orientation = readJpegExifOrientation(fixedBuf);
    expect(orientation).toBeNull();
    // Confirm the candidate-filter predicate is false for a fixed photo:
    expect(orientation !== null && orientation !== 1).toBe(false);
  });

  it("returns null for a non-JPEG buffer without throwing", () => {
    const buf = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]); // PNG header
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  it("returns null for an empty buffer without throwing", () => {
    expect(readJpegExifOrientation(Buffer.alloc(0))).toBeNull();
  });

  it("returns 8 for Orientation=8 (90° CCW — phone portrait stored sideways the other way)", () => {
    const buf = buildJpegWithOrientation(8);
    expect(readJpegExifOrientation(buf)).toBe(8);
  });

  it("returns 3 for Orientation=3 (180° rotation)", () => {
    const buf = buildJpegWithOrientation(3);
    expect(readJpegExifOrientation(buf)).toBe(3);
  });

  // ---- Big-endian ('MM') TIFF synthetic buffers ---------------------------
  // These exercise the BE branch (buf[t] !== 0x49) of readJpegExifOrientation,
  // which is used by many Android OEM cameras.

  it("BE TIFF: returns 6 for Orientation=6 (90° CW — Android portrait)", () => {
    const buf = buildJpegWithOrientationBE(6);
    expect(readJpegExifOrientation(buf)).toBe(6);
  });

  it("BE TIFF: returns 1 for Orientation=1 (upright — must not appear in sideways candidates)", () => {
    const buf = buildJpegWithOrientationBE(1);
    expect(readJpegExifOrientation(buf)).toBe(1);
  });

  it("BE TIFF: returns 8 for Orientation=8 (90° CCW — Android portrait rotated the other way)", () => {
    const buf = buildJpegWithOrientationBE(8);
    expect(readJpegExifOrientation(buf)).toBe(8);
  });
});

// ---------------------------------------------------------------------------
// Suite 1b: BE TIFF truncated-buffer safety.
//
// A broken Android camera app (or a network-corrupted upload) can produce a
// JPEG whose APP1/EXIF payload is cut off mid-TIFF-header.  These tests prove
// that every early-exit bounds check in readJpegExifOrientation fires for
// big-endian ('MM') TIFF headers and that the function returns null rather
// than throwing a RangeError.
//
// Full BE buffer layout (40 bytes total, all offsets absolute):
//   0–1   SOI
//   2–3   APP1 marker
//   4–5   APP1 length (big-endian, = 34)
//   6–11  "Exif\0\0"
//   12–13 TIFF byte-order mark ('M','M')   ← t = 12
//   14–15 TIFF magic 42 (big-endian)
//   16–19 IFD0 offset = 8 (big-endian)
//   20–21 IFD0 entry count = 1              ← ifd0 = t + 8 = 20
//   22–33 12-byte IFD0 entry                ← e = ifd0 + 2 = 22
//   34–37 next-IFD pointer = 0
//   38–39 EOI
//
// Bounds checks under test (from photoExif.ts):
//   A) if (t + 8 >= buf.length) break          → fires when len ≤ 20
//   B) if (ifd0 + 2 >= buf.length) break       → fires when len ≤ 22
//   C) if (e + 10 >= buf.length) break (loop)  → fires when len ≤ 32
// ---------------------------------------------------------------------------

/**
 * Build a minimal BE TIFF JPEG and slice it to `keepBytes` to simulate a
 * truncated upload.  The APP1 length field is deliberately left at the
 * full-buffer value so the segment-walk does not skip the segment — the
 * only difference is that the buffer ends prematurely.
 */
function buildTruncatedJpegBE(orientation: number, keepBytes: number): Buffer {
  return buildJpegWithOrientationBE(orientation).subarray(0, keepBytes);
}

describe("readJpegExifOrientation — BE TIFF truncated-buffer safety", () => {
  // ---- Check A: buffer ends just after the 'MM' byte-order mark ----------
  // keepBytes=14 → buffer covers SOI + APP1 marker + APP1 len + "Exif\0\0" +
  // 'M','M' only (2 bytes of the TIFF header).  The IFD0 offset field
  // (pos 16–19) is missing, so `t + 8 >= buf.length` (20 >= 14) fires.
  it("BE TIFF truncated after byte-order mark: returns null without throwing", () => {
    const buf = buildTruncatedJpegBE(6, 14);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // ---- Check B: buffer ends inside the IFD0 count field ------------------
  // keepBytes=21 → the IFD0 count field at pos 20–21 is only partially
  // present (1 byte).  `ifd0 + 2 >= buf.length` (22 >= 21) fires.
  it("BE TIFF truncated inside IFD0 count field: returns null without throwing", () => {
    const buf = buildTruncatedJpegBE(6, 21);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // ---- Check C: buffer ends mid-entry ------------------------------------
  // keepBytes=28 → the entry starts at pos 22; we have tag (22–23) and type
  // (24–25) and the first two bytes of the 4-byte count field (26–27) but
  // the value field at pos 30–31 is absent.  `e + 10 >= buf.length`
  // (32 >= 28) fires on the first loop iteration.
  it("BE TIFF truncated mid-entry (past count, before value): returns null without throwing", () => {
    const buf = buildTruncatedJpegBE(6, 28);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });
});

// ---------------------------------------------------------------------------
// Suite 1c: LE TIFF truncated-buffer safety.
//
// A broken iOS camera app (or a network-corrupted upload) can produce a JPEG
// whose APP1/EXIF payload is cut off mid-TIFF-header.  These tests prove that
// every early-exit bounds check in readJpegExifOrientation fires for
// little-endian ('II') TIFF headers and that the function returns null rather
// than throwing a RangeError.
//
// Full LE buffer layout (40 bytes total, all offsets absolute):
//   0–1   SOI
//   2–3   APP1 marker
//   4–5   APP1 length (big-endian, = 34)
//   6–11  "Exif\0\0"
//   12–13 TIFF byte-order mark ('I','I')   ← t = 12
//   14–15 TIFF magic 42 (little-endian)
//   16–19 IFD0 offset = 8 (little-endian)
//   20–21 IFD0 entry count = 1              ← ifd0 = t + 8 = 20
//   22–33 12-byte IFD0 entry                ← e = ifd0 + 2 = 22
//   34–37 next-IFD pointer = 0
//   38–39 EOI
//
// Bounds checks under test (from photoExif.ts) — identical to the BE path:
//   A) if (t + 8 >= buf.length) break          → fires when len ≤ 20
//   B) if (ifd0 + 2 >= buf.length) break       → fires when len ≤ 22
//   C) if (e + 10 >= buf.length) break (loop)  → fires when len ≤ 32
// ---------------------------------------------------------------------------

/**
 * Build a minimal LE TIFF JPEG and slice it to `keepBytes` to simulate a
 * truncated upload.  The APP1 length field is deliberately left at the
 * full-buffer value so the segment-walk does not skip the segment — the
 * only difference is that the buffer ends prematurely.
 */
function buildTruncatedJpegLE(orientation: number, keepBytes: number): Buffer {
  return buildJpegWithOrientation(orientation).subarray(0, keepBytes);
}

describe("readJpegExifOrientation — LE TIFF truncated-buffer safety", () => {
  // ---- Check A: buffer ends just after the 'II' byte-order mark ----------
  // keepBytes=14 → buffer covers SOI + APP1 marker + APP1 len + "Exif\0\0" +
  // 'I','I' only (2 bytes of the TIFF header).  The IFD0 offset field
  // (pos 16–19) is missing, so `t + 8 >= buf.length` (20 >= 14) fires.
  it("LE TIFF truncated after byte-order mark: returns null without throwing", () => {
    const buf = buildTruncatedJpegLE(6, 14);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // ---- Check B: buffer ends inside the IFD0 count field ------------------
  // keepBytes=21 → the IFD0 count field at pos 20–21 is only partially
  // present (1 byte).  `ifd0 + 2 >= buf.length` (22 >= 21) fires.
  it("LE TIFF truncated inside IFD0 count field: returns null without throwing", () => {
    const buf = buildTruncatedJpegLE(6, 21);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });

  // ---- Check C: buffer ends mid-entry ------------------------------------
  // keepBytes=28 → the entry starts at pos 22; we have tag (22–23) and type
  // (24–25) and the first two bytes of the 4-byte count field (26–27) but
  // the value field at pos 30–31 is absent.  `e + 10 >= buf.length`
  // (32 >= 28) fires on the first loop iteration.
  it("LE TIFF truncated mid-entry (past count, before value): returns null without throwing", () => {
    const buf = buildTruncatedJpegLE(6, 28);
    expect(readJpegExifOrientation(buf)).toBeNull();
  });
});

// ---------------------------------------------------------------------------
// Suite 2: Synthetic multi-entry EXIF fixtures.
//
// Generated by server/__fixtures__/generate-fixtures.cjs — realistic EXIF
// segments with Make, Model, Orientation, XResolution, YResolution, and
// ResolutionUnit entries matching the structure real phones write.
//
// iPhone-style fixtures use little-endian ('II') TIFF byte order.
// Android-style fixtures use big-endian ('MM') TIFF byte order.
// ---------------------------------------------------------------------------

describe("readJpegExifOrientation — synthetic multi-entry EXIF (LE + BE layouts)", () => {
  // ---- iPhone-style (little-endian TIFF) ----------------------------------

  it("LE TIFF portrait (orientation=6): returns 6 — sideways candidate", () => {
    // Mirrors a photo taken in portrait mode on an iPhone; stored 90° CW.
    expect(readJpegExifOrientation(fixture("iphone_portrait_o6.jpg"))).toBe(6);
  });

  it("LE TIFF upright (orientation=1): returns 1 — must NOT be a candidate", () => {
    // Landscape shot or a photo already re-encoded upright; should be skipped.
    expect(readJpegExifOrientation(fixture("iphone_upright_o1.jpg"))).toBe(1);
  });

  // ---- Android-style (big-endian / Motorola-byte-order TIFF) -------------

  it("BE TIFF portrait (orientation=6): returns 6 — sideways candidate", () => {
    // Many Android OEMs write big-endian ('MM') TIFF headers.
    expect(readJpegExifOrientation(fixture("android_portrait_o6_be.jpg"))).toBe(6);
  });

  it("BE TIFF upright (orientation=1): returns 1 — must NOT be a candidate", () => {
    expect(readJpegExifOrientation(fixture("android_upright_o1_be.jpg"))).toBe(1);
  });

  it("BE TIFF 90° CCW (orientation=8): returns 8 — sideways candidate", () => {
    // Orientation=8 occurs when a phone is rotated the opposite direction.
    expect(readJpegExifOrientation(fixture("android_sideways_o8_be.jpg"))).toBe(8);
  });
});

// ---------------------------------------------------------------------------
// Suite 3: Real unmodified device JPEGs — provenance documented below.
//
// Every file was fetched verbatim from a public open-source fixture repository
// and its orientation was independently verified with `file` (libmagic EXIF
// decoder) before being hard-coded into a test expectation.
//
// The three files that are header-trimmed (iphone4s_o6, iphone5_o3,
// samsung_galaxysii_o6) had their scan payload (everything from the SOS marker
// onwards) removed to keep the committed file small; the EXIF APP1 segment
// that readJpegExifOrientation reads is byte-for-byte identical to the original.
//
// File inventory (all in server/__fixtures__/real/):
//
//   iphone4s_o6.jpg
//       Source  : github.com/drewnoakes/metadata-extractor-images,
//                 jpg/Apple iPhone 4S.jpg (widely-used real-device EXIF test suite)
//       Device  : Apple iPhone 4S (iOS 5.1.1)
//       TIFF BO : big-endian ('MM')   IFD0 entries: 10
//       Orientation: 6 (upper-right — 90° CW, the canonical iPhone portrait)
//       file(1) : TIFF image data, big-endian, direntries=10,
//                 manufacturer=Apple, model=iPhone 4S, orientation=upper-right
//       Note    : Trimmed at SOS marker; original = 3.8 MB; trimmed = 1.3 KB
//
//   iphone5_o3.jpg
//       Source  : github.com/drewnoakes/metadata-extractor-images,
//                 jpg/Apple iPhone 5.jpg
//       Device  : Apple iPhone 5
//       TIFF BO : big-endian ('MM')   IFD0 entries: 11 (includes GPS sub-IFD)
//       Orientation: 3 (lower-right — 180° rotation; a second non-upright value)
//       file(1) : TIFF image data, big-endian, direntries=11,
//                 manufacturer=Apple, model=iPhone 5, orientation=lower-right,
//                 GPS-Data
//       Note    : Trimmed at SOS marker; original = 2.3 MB; trimmed = 1.5 KB
//
//   samsung_galaxysii_o6.jpg
//       Source  : github.com/drewnoakes/metadata-extractor-images,
//                 jpg/Samsung GT-I9100 (Galaxy SII).jpg
//       Device  : Samsung Galaxy SII (Android)
//       TIFF BO : little-endian ('II')   IFD0 entries: 12
//       Orientation: 6 (upper-right — 90° CW portrait, same as the iPhone case)
//       file(1) : TIFF image data, little-endian, direntries=12,
//                 manufacturer=SAMSUNG, model=GT-I9100, orientation=upper-right
//       Note    : Trimmed at SOS marker; original = 3.2 MB; trimmed = 1.5 KB
//       Significance: LE TIFF byte order + non-1 orientation from a real Android
//                 phone — the specific combination that is hardest to synthesise.
//
//   canon_o1.jpg
//       Source  : github.com/recurser/exif-orientation-examples, Landscape_1.jpg
//       Device  : Canon camera (used as a compact real-BE-TIFF baseline)
//       TIFF BO : big-endian ('MM')   IFD0 entries: 5
//       Orientation: 1 (upper-left, upright)
//       file(1) : TIFF image data, big-endian, direntries=5, orientation=upper-left
//
//   canon_portrait_o6.jpg
//       Source  : github.com/recurser/exif-orientation-examples, Portrait_6.jpg
//       Device  : Canon camera
//       TIFF BO : big-endian ('MM')   IFD0 entries: 5
//       Orientation: 6 (upper-right, 90° CW)
//       file(1) : TIFF image data, big-endian, direntries=5, orientation=upper-right
//
//   canon_o8.jpg
//       Source  : github.com/recurser/exif-orientation-examples, Landscape_8.jpg
//       Device  : Canon camera
//       TIFF BO : big-endian ('MM')   IFD0 entries: 5
//       Orientation: 8 (lower-left, 90° CCW)
//       file(1) : TIFF image data, big-endian, direntries=5, orientation=lower-left
//
//   pixel_portrait.jpg
//       Source  : github.com/MikeKovarik/exifr, IMG_20180725_163423.jpg
//       Device  : Google Pixel (Android phone)
//       TIFF BO : little-endian ('II')   IFD0 entries: 13 (includes GPS sub-IFD)
//       Orientation: 1 (upper-left, landscape orientation)
//       file(1) : TIFF image data, little-endian, direntries=13, GPS-Data,
//                 manufacturer=Google, model=Pixel
//       Note    : Trimmed at SOS marker; EXIF segment intact and unchanged.
//
//   cam_Samsung_Digimax_i50_MP3.jpg
//       Source  : github.com/ianare/exif-samples, Samsung_Digimax_i50_MP3.jpg
//       Device  : Samsung Digimax i50 MP3 consumer camera
//       TIFF BO : little-endian ('II')   IFD0 entries: 12
//       Orientation: 1 (upper-left, landscape)
//       file(1) : TIFF image data, little-endian, direntries=12,
//                 manufacturer=Samsung Techwin, model=Digimax i50 MP3
// ---------------------------------------------------------------------------

describe("readJpegExifOrientation — real unmodified device JPEGs", () => {
  // ---- Real Apple iPhone photos -------------------------------------------

  it("iPhone 4S (BE TIFF, o=6): returns 6 — real iPhone portrait, sideways candidate", () => {
    // Apple iPhone 4S.jpg from drewnoakes/metadata-extractor-images.
    // Make=Apple, Model=iPhone 4S, iOS 5.1.1. Orientation=6 (upper-right)
    // is the canonical portrait orientation for iPhones held normally.
    // `file` confirms: TIFF big-endian, direntries=10, orientation=upper-right.
    expect(readJpegExifOrientation(fixture("real/iphone4s_o6.jpg"))).toBe(6);
  });

  it("iPhone 5 (BE TIFF, o=3): returns 3 — real iPhone rotated 180°, sideways candidate", () => {
    // Apple iPhone 5.jpg from drewnoakes/metadata-extractor-images.
    // Make=Apple, Model=iPhone 5. Orientation=3 (lower-right, 180° rotation).
    // 11 IFD0 entries including GPS sub-IFD pointer.
    // `file` confirms: TIFF big-endian, direntries=11, orientation=lower-right.
    expect(readJpegExifOrientation(fixture("real/iphone5_o3.jpg"))).toBe(3);
  });

  // ---- Real Android phone photos (LE TIFF + non-1 orientation) ------------

  it("Samsung Galaxy SII Android (LE TIFF, o=6): returns 6 — real Android portrait, sideways candidate", () => {
    // Samsung GT-I9100 (Galaxy SII).jpg from drewnoakes/metadata-extractor-images.
    // Make=SAMSUNG, Model=GT-I9100, software=I9100XWLPT. LE TIFF byte order
    // ('II') — same byte order used by modern Android phones and iPhones.
    // Orientation=6 (upper-right, 90° CW portrait). 12 IFD0 entries.
    // `file` confirms: TIFF little-endian, direntries=12, orientation=upper-right.
    expect(readJpegExifOrientation(fixture("real/samsung_galaxysii_o6.jpg"))).toBe(6);
  });

  it("Google Pixel Android (LE TIFF, 13-entry IFD0 + GPS, o=1): returns 1 — upright", () => {
    // IMG_20180725_163423.jpg from MikeKovarik/exifr test fixtures.
    // Make=Google, Model=Pixel. LE TIFF, 13 IFD entries including GPS sub-IFD.
    // Orientation=1 (landscape shot, upright). Proves the LE path iterates a
    // large IFD correctly before hitting the Orientation tag.
    expect(readJpegExifOrientation(fixture("real/pixel_portrait.jpg"))).toBe(1);
  });

  // ---- Canon camera real images (BE TIFF baseline) -----------------------

  it("Canon (BE TIFF, o=1): returns 1 — upright, must NOT be a candidate", () => {
    // Landscape_1.jpg from recurser/exif-orientation-examples.
    expect(readJpegExifOrientation(fixture("real/canon_o1.jpg"))).toBe(1);
  });

  it("Canon (BE TIFF, o=6): returns 6 — BE sideways candidate, 90° CW portrait", () => {
    // Portrait_6.jpg from recurser/exif-orientation-examples (252 KB).
    expect(readJpegExifOrientation(fixture("real/canon_portrait_o6.jpg"))).toBe(6);
  });

  it("Canon (BE TIFF, o=8): returns 8 — BE sideways candidate, 90° CCW portrait", () => {
    // Landscape_8.jpg from recurser/exif-orientation-examples.
    expect(readJpegExifOrientation(fixture("real/canon_o8.jpg"))).toBe(8);
  });

  // ---- Real Samsung consumer camera (LE TIFF, 12 entries, o=1) -----------

  it("Samsung Digimax (LE TIFF, 12-entry IFD0, o=1): returns 1 — upright", () => {
    // Samsung_Digimax_i50_MP3.jpg from ianare/exif-samples. LE TIFF, 12 IFD
    // entries (Make, Model, Orientation, XResolution, YResolution, Software,
    // DateTime, Copyright, and more) — iterates many entries to find Orientation.
    expect(readJpegExifOrientation(fixture("real/cam_Samsung_Digimax_i50_MP3.jpg"))).toBe(1);
  });
});
